from enum import Enum


class ErrorCode(str, Enum):
    CALL_NOT_FOUND = "CALL-001"
    CALL_ALREADY_ENDED = "CALL-002"
    CALL_INTERNAL_ERROR = "CALL-003"
    CALL_AI_FAILED = "CALL-004"
    CALL_TTS_FAILED = "CALL-005"
    NEWS_QUERY_ERROR = "NEWS-001"
    NEWS_UPDATE_ERROR = "NEWS-002"
    NEWS_CRAWL_ERROR = "NEWS-003"
    REPORT_NOT_FOUND = "REPORT-001"
    REPORT_INTERNAL_ERROR = "REPORT-002"
