spring:
    datasource:
      url: ${SPRING_DATASOURCE_PROD_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      driver-class-name: org.postgresql.Driver

    data:
      redis:
        host: ${REDIS_HOST} # Docker Compose의 서비스명
        port: ${REDIS_PORT}
        password: ${REDIS_PASSWORD}