"""add custom_audio_url column

Revision ID: ff00a53e07cd
Revises: 0002_update_duration_not_null
Create Date: 2025-03-30 14:16:00.507198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff00a53e07cd'
down_revision: Union[str, None] = '0002_update_duration_not_null'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_voice')
    op.drop_table('member')
    op.drop_index('flyway_schema_history_s_idx', table_name='flyway_schema_history')
    op.drop_table('flyway_schema_history')
    op.drop_table('call_schedule')
    op.drop_table('level')
    op.drop_table('voice')
    op.add_column('call', sa.Column('custom_audio_url', sa.Text(), nullable=True))
    op.alter_column('call', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('call', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('call', 'custom_audio_url')
    op.create_table('voice',
    sa.Column('voice_id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('audio_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True),
    sa.Column('voice_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.CheckConstraint("type::text = ANY (ARRAY['CELEB'::character varying::text, 'CUSTOM'::character varying::text])", name='voice_type_check'),
    sa.PrimaryKeyConstraint('voice_id', name='voice_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('level',
    sa.Column('level_id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('badge_icon', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('min_report_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True),
    sa.Column('min_call_duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('level_id', name='level_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('call_schedule',
    sa.Column('call_schedule_id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('scheduled_day', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('scheduled_time', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('topic_category', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('member_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=False),
    sa.CheckConstraint("scheduled_day::text = ANY (ARRAY['MONDAY'::character varying::text, 'TUESDAY'::character varying::text, 'WEDNESDAY'::character varying::text, 'THURSDAY'::character varying::text, 'FRIDAY'::character varying::text, 'SATURDAY'::character varying::text, 'SUNDAY'::character varying::text])", name='call_schedule_scheduled_day_check'),
    sa.CheckConstraint("topic_category::text = ANY (ARRAY['SPORTS'::character varying::text, 'TRIP'::character varying::text, 'MOVIE'::character varying::text, 'FOOD'::character varying::text, 'GAME'::character varying::text, 'MUSIC'::character varying::text, 'HEALTH'::character varying::text])", name='call_schedule_topic_category_check'),
    sa.PrimaryKeyConstraint('call_schedule_id', name='call_schedule_pkey'),
    sa.UniqueConstraint('member_id', 'scheduled_day', name='uk3plfsuaenmndq8n708yvuhjw3')
    )
    op.create_table('flyway_schema_history',
    sa.Column('installed_rank', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('script', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('installed_by', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('installed_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('execution_time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('installed_rank', name='flyway_schema_history_pk')
    )
    op.create_index('flyway_schema_history_s_idx', 'flyway_schema_history', ['success'], unique=False)
    op.create_table('member',
    sa.Column('member_id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('fcm_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('gender', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('interest', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('selected_voice_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True),
    sa.Column('total_report_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('level_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('total_call_duration', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.CheckConstraint('gender >= 0 AND gender <= 1', name='member_gender_check'),
    sa.ForeignKeyConstraint(['level_id'], ['level.level_id'], name='fkclsk8iy6qqnul2k5v2qtul5ii'),
    sa.PrimaryKeyConstraint('member_id', name='member_pkey'),
    sa.UniqueConstraint('email', name='ukmbmcqelty0fbrvxp1q58dn57t'),
    postgresql_ignore_search_path=False
    )
    op.create_table('member_voice',
    sa.Column('member_voice_id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('activate', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True),
    sa.Column('member_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('voice_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], name='fklqr7dqf1wmtcqrkcuvewu2e75'),
    sa.ForeignKeyConstraint(['voice_id'], ['voice.voice_id'], name='fko4gtw3bmboep0gmq52un33mj9'),
    sa.PrimaryKeyConstraint('member_voice_id', name='member_voice_pkey')
    )
    # ### end Alembic commands ###
